### ISSUE TITLE
[sdformat-9] not building.

### ISSUE THREAD

**Issue by KavinTheG** [acxz/gazebo-arch#62] opened 2023-03-16 23:24 UTC
Target build: sdformat-9
```c++
/home/kavin/.cache/yay/sdformat-9/src/sdformat-sdformat9_9.8.0/src/parser_urdf.cc:30:10: fatal error: urdf_model/model.h: No such file or directory
   30 | #include <urdf_model/model.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/sdformat9.dir/build.make:552: src/CMakeFiles/sdformat9.dir/parser_urdf.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3435: src/CMakeFiles/sdformat9.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: sdformat-9 
``` 
My issue is that when I try to install gazebo/gazebo-git, I am unable to build sdformat-9. 
I am utilising ros2-humble. I also have urdfdom and urdfdom-headers installed.

```
local/urdfdom 3.1.0-1
    The URDF (U-Robot Description Format) library provides core data structures and a simple XML parsers for populating the class data structures from an
    URDF file.
local/urdfdom-headers 1.1.0-1
    The URDF (U-Robot Description Format) headers provides core data structure headers for URDF.
```
Any help would be greatly appreciated!

**Comment by KavinTheG** [comment] 2023-03-17 01:02
It seemed that issue was mainly some sort of include error. I was able to resolve this by pulling the source code for sdformat at https://github.com/gazebosim/sdformat and replacing all occurances of '#include <urdf_*/*> with <urdf/urdf_*/*>.

**Comment by bruno-anjos** [comment] 2023-04-08 10:29
Package still fails building with the same error.

**Comment by acxz** [comment] 2023-06-22 13:20
@bruno-anjos I am not able to reproduce this error. Can you try building in clean chroot and report back?

**Comment by acxz** [comment] 2023-09-26 02:38
closing this error with no response and no reproducibility

**Comment by codeflight1** [comment] 2023-12-22 18:44
I have experienced the same error while installing `sdformat-9`.

**Comment by acxz** [comment] 2023-12-22 19:05
@codeflight1 were you able to try to build in a clean chroot?

**Comment by codeflight1** [comment] 2024-01-01 02:02
I attempted to, but I encountered missing dependency issues with the `ignition-*` packages even after installing them. I'm using `clean-chroot-manager`, not sure if that may have an impact.

**Comment by acxz** [comment] 2024-01-01 15:10
Yep that definitely sounds like a `clean-chroot-manager` usability error. If you want to build in a clean chroot, I'd suggest using `paru`. Please try again with `paru`.

**Comment by codeflight1** [comment] 2024-01-02 04:09
I was able to successfully build with `paru`, and I did not encounter the compilation error.

**Comment by acxz** [comment] 2024-01-02 14:28
Glad to hear! I'll go ahead and close this issue, if you have any more errors feel free to post.

**Closed by acxz** 2024-01-02 14:28 UTC
